worker_processes  1;

error_log  /Path/to/toolbox/nginx/log/toolbox-error.log;
pid        /Path/to/toolbox/nginx/log/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /opt/homebrew/etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;
    client_max_body_size 100M;

    gzip  on;
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        application/xml
        image/svg+xml;

    #------------服务：toolbox---------
    server {
        listen       9010;
        server_name  localhost;

        access_log  /Users/subeipo/Documents/code/toolbox/nginx/log/toolbox-access.log;

        location / {
            root   /Users/subeipo/Documents/code/toolbox/dist;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location = /index.html {
            root       /Users/subeipo/Documents/code/toolbox/dist;
            add_header Cache-Control "no-cache";
        }

        location = /sw.js {
            root       /Users/subeipo/Documents/code/toolbox/dist;
            add_header Cache-Control "no-cache";
        }
    }
}
