import type { ToolDefinition } from './types'

export const tools: ToolDefinition[] = [
  {
    id: 'json',
    title: 'JSON 格式化',
    description: '在浏览器中安全地格式化、压缩和校验 JSON。',
    path: '/tools/json',
    category: 'format',
    group: 'JSON / YAML',
    keywords: ['json', 'formatter', 'validator', 'minify'],
    aliases: ['pretty json', 'jsonlint'],
    featured: true,
    order: 10,
    status: 'active',
    component: () => import('./json/JsonTool.vue'),
  },
  {
    id: 'base64',
    title: 'Base64 编解码',
    description: '编码和解码 Base64 文本。',
    path: '/tools/base64',
    category: 'encode',
    group: 'Text Encoding',
    keywords: ['base64', 'encode', 'decode'],
    aliases: ['b64'],
    order: 10,
    status: 'active',
    component: () => import('./base64/Base64Tool.vue'),
  },
  {
    id: 'html-entity',
    title: 'HTML Entity 编解码',
    description: '编码和解码 HTML 实体文本。',
    path: '/tools/html-entity',
    category: 'encode',
    group: 'Text Encoding',
    keywords: ['html', 'entity', 'encode', 'decode', 'escape'],
    aliases: ['html entities', 'entity decode'],
    order: 30,
    status: 'active',
    component: () => import('./html-entity/HtmlEntityTool.vue'),
  },
  {
    id: 'hex',
    title: 'Hex 编解码',
    description: '在 UTF-8 文本和十六进制字节之间转换。',
    path: '/tools/hex',
    category: 'encode',
    group: 'Number Bases',
    keywords: ['hex', 'hexadecimal', 'bytes', 'encode', 'decode'],
    aliases: ['hex decode', 'hexadecimal'],
    order: 50,
    status: 'active',
    component: () => import('./hex/HexTool.vue'),
  },
  {
    id: 'binary',
    title: 'Binary 编解码',
    description: '在 UTF-8 文本和 8 位二进制字节之间转换。',
    path: '/tools/binary',
    category: 'encode',
    group: 'Number Bases',
    keywords: ['binary', 'base2', 'bytes', 'encode', 'decode'],
    aliases: ['binary decode', 'base2'],
    order: 60,
    status: 'active',
    component: () => import('./binary/BinaryTool.vue'),
  },
  {
    id: 'number-base',
    title: 'Number Base 转换',
    description: '在 2 到 36 进制之间转换整数。',
    path: '/tools/number-base',
    category: 'encode',
    group: 'Number Bases',
    keywords: ['number', 'base', 'radix', 'binary', 'hex', 'octal'],
    aliases: ['base converter', 'radix'],
    order: 70,
    status: 'active',
    component: () => import('./number-base/NumberBaseTool.vue'),
  },
  {
    id: 'ascii',
    title: 'ASCII / 字符码表',
    description: '查看 ASCII 参考表并分析字符码点。',
    path: '/tools/ascii',
    category: 'encode',
    group: 'Reference',
    keywords: ['ascii', 'character', 'code', 'unicode', 'reference'],
    aliases: ['ascii table', 'character code'],
    order: 80,
    status: 'active',
    component: () => import('./ascii/AsciiTool.vue'),
  },
  {
    id: 'gzip',
    title: 'Gzip 压缩 / 解压',
    description: '在 UTF-8 文本和 Gzip Base64 之间压缩与解压。',
    path: '/tools/gzip',
    category: 'encode',
    group: 'Compression',
    keywords: ['gzip', 'compression', 'compress', 'decompress', 'base64'],
    aliases: ['gzip decode', 'gzip base64'],
    order: 90,
    status: 'active',
    component: () => import('./gzip/GzipTool.vue'),
  },
  {
    id: 'brotli',
    title: 'Brotli 压缩 / 解压',
    description: '在 UTF-8 文本和 Brotli Base64 之间压缩与解压。',
    path: '/tools/brotli',
    category: 'encode',
    group: 'Compression',
    keywords: ['brotli', 'br', 'compression', 'compress', 'decompress', 'base64'],
    aliases: ['brotli decode', 'br base64'],
    order: 100,
    status: 'active',
    component: () => import('./brotli/BrotliTool.vue'),
  },
  {
    id: 'unicode-escape',
    title: 'Unicode Escape 编解码',
    description: '在文本和 \\uXXXX Unicode 转义之间转换。',
    path: '/tools/unicode-escape',
    category: 'encode',
    group: 'Text Encoding',
    keywords: ['unicode', 'escape', 'encode', 'decode', 'u'],
    aliases: ['unicode escape', 'u escape'],
    order: 40,
    status: 'active',
    component: () => import('./unicode-escape/UnicodeEscapeTool.vue'),
  },
  {
    id: 'json-organize',
    title: 'JSON 排序 / 去重',
    description: '递归排序 JSON 键、移除数组重复项，并生成可复制字段路径。',
    path: '/tools/json-organize',
    category: 'format',
    group: 'JSON / YAML',
    keywords: ['json', 'sort', 'dedupe', 'unique', 'path', 'jsonpath'],
    aliases: ['json sort', 'json dedupe', 'json path'],
    order: 15,
    status: 'active',
    component: () => import('./json-organize/JsonOrganizeTool.vue'),
  },
  {
    id: 'url',
    title: 'URL 编解码',
    description: '编码和解码 URL 组件。',
    path: '/tools/url',
    category: 'encode',
    group: 'URL',
    keywords: ['url', 'uri', 'encode', 'decode'],
    aliases: ['percent encoding', 'escape'],
    order: 20,
    status: 'active',
    component: () => import('./url/UrlTool.vue'),
  },
  {
    id: 'timestamp',
    title: '时间戳转换',
    description: '转换 Unix 时间戳和本地日期字符串。',
    path: '/tools/timestamp',
    category: 'time',
    group: 'Date Time',
    keywords: ['time', 'timestamp', 'unix', 'date'],
    aliases: ['epoch', 'unix time'],
    featured: true,
    order: 10,
    status: 'active',
    component: () => import('./timestamp/TimestampTool.vue'),
  },
  {
    id: 'jwt',
    title: 'JWT 解码',
    description: '本地解码 JWT 标头和载荷，不会上传令牌。',
    path: '/tools/jwt',
    category: 'security',
    group: 'Token',
    keywords: ['jwt', 'token', 'decode', 'header', 'payload'],
    aliases: ['jsonwebtoken', 'bearer'],
    featured: true,
    order: 10,
    status: 'active',
    component: () => import('./jwt/JwtTool.vue'),
  },
  {
    id: 'jwt-sign',
    title: 'JWT 编码 / 签名 / 验签',
    description: '本地签发 HMAC JWT 并验证 JWT 签名。',
    path: '/tools/jwt-sign',
    category: 'security',
    group: 'Token',
    keywords: ['jwt', 'token', 'sign', 'verify', 'hmac', 'hs256'],
    aliases: ['jwt sign', 'jwt verify'],
    order: 15,
    status: 'active',
    component: () => import('./jwt-sign/JwtSignTool.vue'),
  },
  {
    id: 'jwk-pem',
    title: 'JWK / PEM 转换',
    description: '在 RSA JWK JSON 和 PEM 公私钥之间转换。',
    path: '/tools/jwk-pem',
    category: 'security',
    group: 'Key',
    keywords: ['jwk', 'pem', 'rsa', 'key', 'public key', 'private key'],
    aliases: ['jwk to pem', 'pem to jwk'],
    order: 20,
    status: 'active',
    component: () => import('./jwk-pem/JwkPemTool.vue'),
  },
  {
    id: 'hash',
    title: '哈希生成',
    description: '生成浏览器原生 SHA 摘要。',
    path: '/tools/hash',
    category: 'security',
    group: 'Digest',
    keywords: ['hash', 'sha', 'digest', 'crypto'],
    aliases: ['sha256', 'checksum'],
    order: 20,
    status: 'active',
    component: () => import('./hash/HashTool.vue'),
  },
  {
    id: 'hmac',
    title: 'HMAC 生成',
    description: '使用 SHA 系列算法生成 HMAC 签名。',
    path: '/tools/hmac',
    category: 'security',
    group: 'Digest',
    keywords: ['hmac', 'sha', 'signature', 'digest', 'secret'],
    aliases: ['hmac sha256', 'signature hash'],
    order: 30,
    status: 'active',
    component: () => import('./hmac/HmacTool.vue'),
  },
  {
    id: 'uuid',
    title: 'UUID 生成',
    description: '生成随机 UUID 值。',
    path: '/tools/uuid',
    category: 'generate',
    group: 'Identifiers',
    keywords: ['uuid', 'guid', 'random'],
    aliases: ['id generator'],
    order: 10,
    status: 'active',
    component: () => import('./uuid/UuidTool.vue'),
  },
  {
    id: 'json-type',
    title: 'JSON 转类型',
    description: '从 JSON 样例生成 TypeScript、Java、Go 和 Zod 类型。',
    path: '/tools/json-type',
    category: 'code',
    group: 'Types',
    keywords: ['json', 'type', 'typescript', 'interface', 'java', 'go', 'zod', 'schema'],
    aliases: ['interface generator', 'schema generator', 'pojo', 'struct'],
    featured: true,
    order: 10,
    status: 'active',
    component: () => import('./json-type/JsonTypeTool.vue'),
  },
  {
    id: 'jsonpath',
    title: 'JSONPath 查询器',
    description: '用 JSONPath 表达式查询 JSON，并复制命中路径和值。',
    path: '/tools/jsonpath',
    category: 'code',
    group: 'Query',
    keywords: ['jsonpath', 'json', 'query', 'path', 'filter'],
    aliases: ['json query', 'json path tester'],
    order: 30,
    status: 'active',
    component: () => import('./jsonpath/JsonPathTool.vue'),
  },
  {
    id: 'json-schema-generate',
    title: 'JSON Schema 生成器',
    description: '从 JSON 样例推断基础 JSON Schema。',
    path: '/tools/json-schema-generate',
    category: 'code',
    group: 'Schema',
    keywords: ['json', 'schema', 'generate', 'infer'],
    aliases: ['schema generator', 'json schema infer'],
    order: 40,
    status: 'active',
    component: () => import('./json-schema-generate/JsonSchemaGenerateTool.vue'),
  },
  {
    id: 'json-patch',
    title: 'JSON Patch / Merge Patch',
    description: '对比两个 JSON 文档并生成 JSON Patch 或 Merge Patch。',
    path: '/tools/json-patch',
    category: 'code',
    group: 'JSON / YAML',
    keywords: ['json', 'patch', 'merge patch', 'diff'],
    aliases: ['json diff', 'rfc6902', 'rfc7396'],
    order: 50,
    status: 'active',
    component: () => import('./json-patch/JsonPatchTool.vue'),
  },
  {
    id: 'yaml-json',
    title: 'YAML / JSON 转换',
    description: '在 JSON 和 YAML 配置格式之间互相转换。',
    path: '/tools/yaml-json',
    category: 'format',
    group: 'JSON / YAML',
    keywords: ['yaml', 'json', 'convert', 'config'],
    aliases: ['yml', 'configuration'],
    featured: true,
    order: 20,
    status: 'active',
    component: () => import('./yaml-json/YamlJsonTool.vue'),
  },
  {
    id: 'markdown-preview',
    title: 'Markdown 预览',
    description: '在本地渲染 Markdown，并查看标题结构、字数和 HTML 输出。',
    path: '/tools/markdown-preview',
    category: 'format',
    group: 'Markdown',
    keywords: ['markdown', 'md', 'preview', 'render', 'html'],
    aliases: ['markdown renderer', 'md preview'],
    order: 120,
    status: 'active',
    component: () => import('./markdown-preview/MarkdownPreviewTool.vue'),
  },
  {
    id: 'html',
    title: 'HTML 格式化',
    description: '格式化或压缩 HTML 标记文本。',
    path: '/tools/html',
    category: 'format',
    group: 'Web Markup',
    keywords: ['html', 'format', 'formatter', 'minify', 'markup'],
    aliases: ['html formatter', 'html minifier'],
    order: 130,
    status: 'active',
    component: () => import('./html/HtmlTool.vue'),
  },
  {
    id: 'sitemap',
    title: 'XML Sitemap 格式化',
    description: '格式化并校验 XML Sitemap urlset 或 sitemapindex。',
    path: '/tools/sitemap',
    category: 'format',
    group: 'Web Markup',
    keywords: ['xml', 'sitemap', 'seo', 'urlset', 'sitemapindex'],
    aliases: ['sitemap validator', 'xml sitemap'],
    order: 135,
    status: 'active',
    component: () => import('./sitemap/SitemapTool.vue'),
  },
  {
    id: 'css',
    title: 'CSS 格式化',
    description: '格式化或压缩 CSS 样式代码。',
    path: '/tools/css',
    category: 'format',
    group: 'Web Code',
    keywords: ['css', 'format', 'formatter', 'minify', 'style'],
    aliases: ['css formatter', 'css minifier'],
    order: 140,
    status: 'active',
    component: () => import('./css/CssTool.vue'),
  },
  {
    id: 'js-ts-format',
    title: 'JavaScript / TypeScript 格式化',
    description: '本地格式化 JavaScript 和 TypeScript 源码，不执行输入内容。',
    path: '/tools/js-ts-format',
    category: 'format',
    group: 'Web Code',
    keywords: ['javascript', 'typescript', 'js', 'ts', 'format', 'formatter'],
    aliases: ['javascript formatter', 'typescript formatter'],
    order: 150,
    status: 'active',
    component: () => import('./js-ts-format/JsTsFormatTool.vue'),
  },
  {
    id: 'markdown-toc',
    title: 'Markdown TOC 生成',
    description: '从 Markdown 标题生成可复制的目录链接。',
    path: '/tools/markdown-toc',
    category: 'text',
    group: 'Markdown',
    keywords: ['markdown', 'toc', 'heading', 'anchor', 'docs'],
    aliases: ['markdown toc', 'table of contents'],
    order: 40,
    status: 'active',
    component: () => import('./markdown-toc/MarkdownTocTool.vue'),
  },
  {
    id: 'cron',
    title: 'Cron 表达式解析',
    description: '解析 Cron 表达式并计算下一批执行时间。',
    path: '/tools/cron',
    category: 'time',
    group: 'Schedule',
    keywords: ['cron', 'schedule', 'time', 'crontab'],
    aliases: ['scheduler', 'next run'],
    order: 20,
    status: 'active',
    component: () => import('./cron/CronTool.vue'),
  },
  {
    id: 'curl',
    title: 'cURL 转代码',
    description: '把常见 cURL 请求转换为 Fetch、Axios 或 Python requests。',
    path: '/tools/curl',
    category: 'code',
    group: 'HTTP',
    keywords: ['curl', 'fetch', 'axios', 'python', 'requests', 'http'],
    aliases: ['api client', 'request code'],
    featured: true,
    order: 20,
    status: 'active',
    component: () => import('./curl/CurlTool.vue'),
  },
  {
    id: 'sql',
    title: 'SQL 格式化',
    description: '格式化或压缩 SQL 查询片段。',
    path: '/tools/sql',
    category: 'format',
    group: 'Database',
    keywords: ['sql', 'format', 'formatter', 'query'],
    aliases: ['database', 'mysql', 'postgres'],
    featured: true,
    order: 30,
    status: 'active',
    component: () => import('./sql/SqlTool.vue'),
  },
  {
    id: 'xml',
    title: 'XML 格式化',
    description: '格式化、压缩并校验 XML 文档。',
    path: '/tools/xml',
    category: 'format',
    group: 'XML',
    keywords: ['xml', 'format', 'formatter', 'minify', 'validate'],
    aliases: ['xml formatter', 'xml validator'],
    order: 50,
    status: 'active',
    component: () => import('./xml/XmlTool.vue'),
  },
  {
    id: 'xml-json',
    title: 'XML / JSON 转换',
    description: '在 XML 和 JSON 表示之间互相转换。',
    path: '/tools/xml-json',
    category: 'format',
    group: 'XML',
    keywords: ['xml', 'json', 'convert', 'transform'],
    aliases: ['xml to json', 'json to xml'],
    order: 60,
    status: 'active',
    component: () => import('./xml-json/XmlJsonTool.vue'),
  },
  {
    id: 'xml-xpath',
    title: 'XML 校验 / XPath 测试',
    description: '校验 XML 并执行 XPath 表达式查看匹配节点。',
    path: '/tools/xml-xpath',
    category: 'format',
    group: 'XML',
    keywords: ['xml', 'xpath', 'validate', 'query'],
    aliases: ['xpath tester', 'xml query'],
    order: 70,
    status: 'active',
    component: () => import('./xml-xpath/XmlXPathTool.vue'),
  },
  {
    id: 'toml',
    title: 'TOML 格式化 / JSON 转换',
    description: '格式化 TOML，并在 TOML 与 JSON 之间转换。',
    path: '/tools/toml',
    category: 'format',
    group: 'Config',
    keywords: ['toml', 'json', 'config', 'format', 'convert'],
    aliases: ['toml formatter', 'toml to json'],
    order: 80,
    status: 'active',
    component: () => import('./toml/TomlTool.vue'),
  },
  {
    id: 'ini-properties',
    title: 'INI / Properties 转换',
    description: '在 INI、Java properties 和 JSON 对象之间转换。',
    path: '/tools/ini-properties',
    category: 'format',
    group: 'Config',
    keywords: ['ini', 'properties', 'json', 'config', 'convert'],
    aliases: ['ini converter', 'properties converter'],
    order: 90,
    status: 'active',
    component: () => import('./ini-properties/IniPropertiesTool.vue'),
  },
  {
    id: 'csv-json',
    title: 'CSV / JSON 转换',
    description: '在 CSV 文本和 JSON 对象数组之间转换。',
    path: '/tools/csv-json',
    category: 'format',
    group: 'CSV',
    keywords: ['csv', 'json', 'convert', 'table'],
    aliases: ['csv to json', 'json to csv'],
    order: 100,
    status: 'active',
    component: () => import('./csv-json/CsvJsonTool.vue'),
  },
  {
    id: 'csv-table',
    title: 'CSV 表格查看器',
    description: '预览 CSV、TSV 和自定义分隔符表格，检查表头与列数问题。',
    path: '/tools/csv-table',
    category: 'format',
    group: 'CSV',
    keywords: ['csv', 'tsv', 'table', 'preview', 'delimiter'],
    aliases: ['csv viewer', 'table preview'],
    order: 110,
    status: 'active',
    component: () => import('./csv-table/CsvTableTool.vue'),
  },
  {
    id: 'csv-sql',
    title: 'CSV / SQL INSERT 生成',
    description: '把 CSV 数据转换成可复制的多行 SQL INSERT 语句。',
    path: '/tools/csv-sql',
    category: 'code',
    group: 'Database',
    keywords: ['csv', 'sql', 'insert', 'database', 'seed'],
    aliases: ['csv to sql', 'insert generator'],
    order: 35,
    status: 'active',
    component: () => import('./csv-sql/CsvSqlTool.vue'),
  },
  {
    id: 'json-schema-validate',
    title: 'JSON Schema 校验',
    description: '用 JSON Schema 在本地校验 JSON 数据并定位错误路径。',
    path: '/tools/json-schema-validate',
    category: 'format',
    group: 'Schema',
    keywords: ['json', 'schema', 'validate', 'validator'],
    aliases: ['json schema validator', 'schema validation'],
    order: 40,
    status: 'active',
    component: () => import('./json-schema-validate/JsonSchemaValidateTool.vue'),
  },
  {
    id: 'regex',
    title: '正则测试',
    description: '用示例文本测试正则表达式。',
    path: '/tools/regex',
    category: 'text',
    group: 'Text Analysis',
    keywords: ['regex', 'regexp', 'pattern', 'match'],
    aliases: ['regular expression'],
    order: 10,
    status: 'active',
    component: () => import('./regex/RegexTool.vue'),
  },
  {
    id: 'diff',
    title: '文本对比',
    description: '在浏览器中对比两段文本。',
    path: '/tools/diff',
    category: 'text',
    group: 'Text Analysis',
    keywords: ['diff', 'compare', 'text'],
    aliases: ['compare text', 'line diff'],
    order: 20,
    status: 'active',
    component: () => import('./diff/DiffTool.vue'),
  },
  {
    id: 'case',
    title: '命名格式转换',
    description: '在常见命名格式之间转换文本。',
    path: '/tools/case',
    category: 'text',
    group: 'Text Transform',
    keywords: ['case', 'camel', 'snake', 'kebab', 'pascal'],
    aliases: ['naming', 'identifier'],
    order: 30,
    status: 'active',
    component: () => import('./case/CaseTool.vue'),
  },
]

export function getToolById(toolId: string) {
  return tools.find((tool) => tool.id === toolId)
}

export function getToolByPath(path: string) {
  return tools.find((tool) => tool.path === path)
}
