import type { ToolDefinition } from './types'

const registeredTools: ToolDefinition[] = [
  {
    id: 'json',
    title: 'JSON 格式化',
    description: '在浏览器中安全地格式化、压缩和校验 JSON。',
    path: '/tools/json',
    category: 'format',
    group: 'JSON / YAML',
    keywords: ['json', 'formatter', 'validator', 'minify'],
    aliases: ['pretty json', 'jsonlint'],
    featured: true,
    order: 10,
    status: 'active',
    component: () => import('./json/JsonTool.vue'),
  },
  {
    id: 'base64',
    title: 'Base64 编解码',
    description: '编码和解码 Base64 文本。',
    path: '/tools/base64',
    category: 'encode',
    group: 'Text Encoding',
    keywords: ['base64', 'encode', 'decode'],
    aliases: ['b64'],
    order: 10,
    status: 'active',
    component: () => import('./base64/Base64Tool.vue'),
  },
  {
    id: 'html-entity',
    title: 'HTML Entity 编解码',
    description: '编码和解码 HTML 实体文本。',
    path: '/tools/html-entity',
    category: 'encode',
    group: 'Text Encoding',
    keywords: ['html', 'entity', 'encode', 'decode', 'escape'],
    aliases: ['html entities', 'entity decode'],
    order: 30,
    status: 'active',
    component: () => import('./html-entity/HtmlEntityTool.vue'),
  },
  {
    id: 'hex',
    title: 'Hex 编解码',
    description: '在 UTF-8 文本和十六进制字节之间转换。',
    path: '/tools/hex',
    category: 'encode',
    group: 'Number Bases',
    keywords: ['hex', 'hexadecimal', 'bytes', 'encode', 'decode'],
    aliases: ['hex decode', 'hexadecimal'],
    order: 50,
    status: 'active',
    component: () => import('./hex/HexTool.vue'),
  },
  {
    id: 'binary',
    title: 'Binary 编解码',
    description: '在 UTF-8 文本和 8 位二进制字节之间转换。',
    path: '/tools/binary',
    category: 'encode',
    group: 'Number Bases',
    keywords: ['binary', 'base2', 'bytes', 'encode', 'decode'],
    aliases: ['binary decode', 'base2'],
    order: 60,
    status: 'active',
    component: () => import('./binary/BinaryTool.vue'),
  },
  {
    id: 'number-base',
    title: 'Number Base 转换',
    description: '在 2 到 36 进制之间转换整数。',
    path: '/tools/number-base',
    category: 'encode',
    group: 'Number Bases',
    keywords: ['number', 'base', 'radix', 'binary', 'hex', 'octal'],
    aliases: ['base converter', 'radix'],
    order: 70,
    status: 'active',
    component: () => import('./number-base/NumberBaseTool.vue'),
  },
  {
    id: 'ascii',
    title: 'ASCII / 字符码表',
    description: '查看 ASCII 参考表并分析字符码点。',
    path: '/tools/ascii',
    category: 'encode',
    group: 'Reference',
    keywords: ['ascii', 'character', 'code', 'unicode', 'reference'],
    aliases: ['ascii table', 'character code'],
    order: 80,
    status: 'active',
    component: () => import('./ascii/AsciiTool.vue'),
  },
  {
    id: 'gzip',
    title: 'Gzip 压缩 / 解压',
    description: '在 UTF-8 文本和 Gzip Base64 之间压缩与解压。',
    path: '/tools/gzip',
    category: 'encode',
    group: 'Compression',
    keywords: ['gzip', 'compression', 'compress', 'decompress', 'base64'],
    aliases: ['gzip decode', 'gzip base64'],
    order: 90,
    status: 'active',
    component: () => import('./gzip/GzipTool.vue'),
  },
  {
    id: 'brotli',
    title: 'Brotli 压缩 / 解压',
    description: '在 UTF-8 文本和 Brotli Base64 之间压缩与解压。',
    path: '/tools/brotli',
    category: 'encode',
    group: 'Compression',
    keywords: ['brotli', 'br', 'compression', 'compress', 'decompress', 'base64'],
    aliases: ['brotli decode', 'br base64'],
    order: 100,
    status: 'active',
    component: () => import('./brotli/BrotliTool.vue'),
  },
  {
    id: 'qr-decode',
    title: 'QR Code 解码',
    description: '从本地图片中识别和解码 QR Code 内容。',
    path: '/tools/qr-decode',
    category: 'encode',
    group: 'QR Code',
    keywords: ['qr', 'qrcode', 'decode', 'scan', 'image'],
    aliases: ['qr decoder', 'scan qr'],
    order: 10,
    status: 'active',
    component: () => import('./qr-decode/QrDecodeTool.vue'),
  },
  {
    id: 'unicode-escape',
    title: 'Unicode Escape 编解码',
    description: '在文本和 \\uXXXX Unicode 转义之间转换。',
    path: '/tools/unicode-escape',
    category: 'encode',
    group: 'Text Encoding',
    keywords: ['unicode', 'escape', 'encode', 'decode', 'u'],
    aliases: ['unicode escape', 'u escape'],
    order: 40,
    status: 'active',
    component: () => import('./unicode-escape/UnicodeEscapeTool.vue'),
  },
  {
    id: 'json-organize',
    title: 'JSON 排序 / 去重',
    description: '递归排序 JSON 键、移除数组重复项，并生成可复制字段路径。',
    path: '/tools/json-organize',
    category: 'format',
    group: 'JSON / YAML',
    keywords: ['json', 'sort', 'dedupe', 'unique', 'path', 'jsonpath'],
    aliases: ['json sort', 'json dedupe', 'json path'],
    order: 15,
    status: 'active',
    component: () => import('./json-organize/JsonOrganizeTool.vue'),
  },
  {
    id: 'url',
    title: 'URL 编解码',
    description: '编码和解码 URL 组件。',
    path: '/tools/url',
    category: 'encode',
    group: 'URL',
    keywords: ['url', 'uri', 'encode', 'decode'],
    aliases: ['percent encoding', 'escape'],
    order: 20,
    status: 'active',
    component: () => import('./url/UrlTool.vue'),
  },
  {
    id: 'timestamp',
    title: '时间戳转换',
    description: '转换 Unix 时间戳和本地日期字符串。',
    path: '/tools/timestamp',
    category: 'time',
    group: 'Date Time',
    keywords: ['time', 'timestamp', 'unix', 'date'],
    aliases: ['epoch', 'unix time'],
    featured: true,
    order: 10,
    status: 'active',
    component: () => import('./timestamp/TimestampTool.vue'),
  },
  {
    id: 'jwt',
    title: 'JWT 解码',
    description: '本地解码 JWT 标头和载荷，不会上传令牌。',
    path: '/tools/jwt',
    category: 'security',
    group: 'Token',
    keywords: ['jwt', 'token', 'decode', 'header', 'payload'],
    aliases: ['jsonwebtoken', 'bearer'],
    featured: true,
    order: 10,
    status: 'active',
    component: () => import('./jwt/JwtTool.vue'),
  },
  {
    id: 'jwt-sign',
    title: 'JWT 编码 / 签名 / 验签',
    description: '本地签发 HMAC JWT 并验证 JWT 签名。',
    path: '/tools/jwt-sign',
    category: 'security',
    group: 'Token',
    keywords: ['jwt', 'token', 'sign', 'verify', 'hmac', 'hs256'],
    aliases: ['jwt sign', 'jwt verify'],
    order: 15,
    status: 'active',
    component: () => import('./jwt-sign/JwtSignTool.vue'),
  },
  {
    id: 'totp',
    title: 'TOTP 生成 / 校验',
    description: '基于 Base32 secret 生成和校验 TOTP 动态验证码。',
    path: '/tools/totp',
    category: 'security',
    group: 'Token',
    keywords: ['totp', 'otp', '2fa', 'mfa', 'authenticator'],
    aliases: ['otp', '2fa'],
    order: 20,
    status: 'active',
    component: () => import('./totp/TotpTool.vue'),
  },
  {
    id: 'oauth-url',
    title: 'OAuth URL 生成器',
    description: '生成 OAuth/OIDC 授权端点 URL，支持 scope、state、PKCE 和额外参数。',
    path: '/tools/oauth-url',
    category: 'security',
    group: 'OAuth',
    keywords: ['oauth', 'oidc', 'authorization', 'url', 'pkce'],
    aliases: ['oauth authorize url', 'authorization url'],
    order: 10,
    status: 'active',
    component: () => import('./oauth-url/OAuthUrlTool.vue'),
  },
  {
    id: 'ip-cidr',
    title: 'IP / CIDR 计算器',
    description: '计算 IPv4 CIDR 的网络地址、广播地址、主机范围和掩码。',
    path: '/tools/ip-cidr',
    category: 'security',
    group: 'Network',
    keywords: ['ip', 'cidr', 'subnet', 'network', 'ipv4'],
    aliases: ['cidr calculator', 'subnet calculator'],
    order: 10,
    status: 'active',
    component: () => import('./ip-cidr/IpCidrTool.vue'),
  },
  {
    id: 'ip-convert',
    title: 'IPv4 / IPv6 转换',
    description: '把 IPv4 转换为整数、HEX、二进制和 IPv4-mapped IPv6 表示。',
    path: '/tools/ip-convert',
    category: 'security',
    group: 'Network',
    keywords: ['ip', 'ipv4', 'ipv6', 'integer', 'hex', 'binary'],
    aliases: ['ipv4 converter', 'ipv6 mapped'],
    order: 20,
    status: 'active',
    component: () => import('./ip-convert/IpConvertTool.vue'),
  },
  {
    id: 'mac-address',
    title: 'MAC 地址格式化 / 厂商查询',
    description: '规范化 MAC 地址，并通过内置 OUI 小表查询厂商。',
    path: '/tools/mac-address',
    category: 'security',
    group: 'Network',
    keywords: ['mac', 'oui', 'vendor', 'network', 'address'],
    aliases: ['mac formatter', 'oui lookup'],
    order: 30,
    status: 'active',
    component: () => import('./mac-address/MacAddressTool.vue'),
  },
  {
    id: 'x509-cert',
    title: 'X.509 证书解析',
    description: '解析 PEM X.509 证书的主体、签发者、有效期、公钥算法和 SAN 域名。',
    path: '/tools/x509-cert',
    category: 'security',
    group: 'Certificate',
    keywords: ['x509', 'certificate', 'tls', 'ssl', 'pem', 'san'],
    aliases: ['certificate parser', 'tls cert'],
    order: 10,
    status: 'active',
    component: () => import('./x509-cert/X509CertTool.vue'),
  },
  {
    id: 'csr',
    title: 'CSR 解析',
    description: '解析 PEM 证书签名请求的主体、公钥算法、签名算法和 SAN 域名。',
    path: '/tools/csr',
    category: 'security',
    group: 'Certificate',
    keywords: ['csr', 'certificate request', 'pkcs10', 'pem', 'san'],
    aliases: ['csr parser', 'certificate request'],
    order: 20,
    status: 'active',
    component: () => import('./csr/CsrTool.vue'),
  },
  {
    id: 'jwk-pem',
    title: 'JWK / PEM 转换',
    description: '在 RSA JWK JSON 和 PEM 公私钥之间转换。',
    path: '/tools/jwk-pem',
    category: 'security',
    group: 'Key',
    keywords: ['jwk', 'pem', 'rsa', 'key', 'public key', 'private key'],
    aliases: ['jwk to pem', 'pem to jwk'],
    order: 20,
    status: 'active',
    component: () => import('./jwk-pem/JwkPemTool.vue'),
  },
  {
    id: 'rsa-key',
    title: 'RSA 密钥生成',
    description: '生成 RSA 公私钥并导出 PEM 与 JWK。',
    path: '/tools/rsa-key',
    category: 'security',
    group: 'Key',
    keywords: ['rsa', 'key', 'generate', 'pem', 'jwk', 'keypair'],
    aliases: ['rsa generator', 'rsa keypair'],
    order: 30,
    status: 'active',
    component: () => import('./rsa-key/RsaKeyTool.vue'),
  },
  {
    id: 'ssh-key',
    title: 'SSH Key Inspector',
    description: '检查 OpenSSH 公钥和私钥 armor 的类型、位数、指纹和注释。',
    path: '/tools/ssh-key',
    category: 'security',
    group: 'Key',
    keywords: ['ssh', 'key', 'public key', 'private key', 'fingerprint', 'authorized_keys'],
    aliases: ['ssh public key', 'authorized_keys'],
    order: 40,
    status: 'active',
    component: () => import('./ssh-key/SshKeyTool.vue'),
  },
  {
    id: 'rsa-sign',
    title: 'RSA 签名 / 验签',
    description: '使用 RSA PEM 密钥生成和验证签名。',
    path: '/tools/rsa-sign',
    category: 'security',
    group: 'Signature',
    keywords: ['rsa', 'sign', 'verify', 'signature', 'pss', 'pkcs1'],
    aliases: ['rsa verify', 'rsa signature'],
    order: 10,
    status: 'active',
    component: () => import('./rsa-sign/RsaSignTool.vue'),
  },
  {
    id: 'ecdsa-sign',
    title: 'ECDSA 签名 / 验签',
    description: '使用 ECDSA PEM 密钥生成和验证签名。',
    path: '/tools/ecdsa-sign',
    category: 'security',
    group: 'Signature',
    keywords: ['ecdsa', 'ec', 'sign', 'verify', 'signature', 'p-256'],
    aliases: ['ecdsa verify', 'ec signature'],
    order: 20,
    status: 'active',
    component: () => import('./ecdsa-sign/EcdsaSignTool.vue'),
  },
  {
    id: 'bcrypt',
    title: 'bcrypt 哈希 / 校验',
    description: '生成 bcrypt 密码哈希并校验密码。',
    path: '/tools/bcrypt',
    category: 'security',
    group: 'Password',
    keywords: ['bcrypt', 'password', 'hash', 'verify', 'compare'],
    aliases: ['bcrypt verify', 'password hash'],
    order: 10,
    status: 'active',
    component: () => import('./bcrypt/BcryptTool.vue'),
  },
  {
    id: 'aes',
    title: 'AES 加密 / 解密',
    description: '使用 AES-GCM 在本地加密和解密文本。',
    path: '/tools/aes',
    category: 'security',
    group: 'Encryption',
    keywords: ['aes', 'gcm', 'encrypt', 'decrypt', 'crypto'],
    aliases: ['aes gcm', 'aes decrypt'],
    order: 10,
    status: 'active',
    component: () => import('./aes/AesTool.vue'),
  },
  {
    id: 'hash',
    title: '哈希生成',
    description: '生成浏览器原生 SHA 摘要。',
    path: '/tools/hash',
    category: 'security',
    group: 'Digest',
    keywords: ['hash', 'sha', 'digest', 'crypto'],
    aliases: ['sha256', 'checksum'],
    order: 20,
    status: 'active',
    component: () => import('./hash/HashTool.vue'),
  },
  {
    id: 'hmac',
    title: 'HMAC 生成',
    description: '使用 SHA 系列算法生成 HMAC 签名。',
    path: '/tools/hmac',
    category: 'security',
    group: 'Digest',
    keywords: ['hmac', 'sha', 'signature', 'digest', 'secret'],
    aliases: ['hmac sha256', 'signature hash'],
    order: 30,
    status: 'active',
    component: () => import('./hmac/HmacTool.vue'),
  },
  {
    id: 'uuid',
    title: 'UUID 生成',
    description: '生成随机 UUID 值。',
    path: '/tools/uuid',
    category: 'generate',
    group: 'Identifiers',
    keywords: ['uuid', 'guid', 'random'],
    aliases: ['id generator'],
    order: 10,
    status: 'active',
    component: () => import('./uuid/UuidTool.vue'),
  },
  {
    id: 'snowflake',
    title: 'Snowflake ID 解析 / 生成',
    description: '解析和生成 Twitter 风格 Snowflake ID 的时间、worker 和序列号。',
    path: '/tools/snowflake',
    category: 'generate',
    group: 'Identifiers',
    keywords: ['snowflake', 'id', 'twitter', 'discord', 'timestamp'],
    aliases: ['twitter snowflake', 'discord snowflake'],
    order: 20,
    status: 'active',
    component: () => import('./snowflake/SnowflakeTool.vue'),
  },
  {
    id: 'ulid',
    title: 'ULID 生成',
    description: '生成可排序 ULID，并解析其中的毫秒时间戳。',
    path: '/tools/ulid',
    category: 'generate',
    group: 'Identifiers',
    keywords: ['ulid', 'id', 'sortable', 'identifier', 'timestamp'],
    aliases: ['sortable id', 'ulid generator'],
    order: 30,
    status: 'active',
    component: () => import('./ulid/UlidTool.vue'),
  },
  {
    id: 'nanoid',
    title: 'Nano ID 生成',
    description: '用可配置长度和字符集生成短随机 ID。',
    path: '/tools/nanoid',
    category: 'generate',
    group: 'Identifiers',
    keywords: ['nanoid', 'nano id', 'id', 'random', 'identifier'],
    aliases: ['nano id', 'nanoid'],
    order: 40,
    status: 'active',
    component: () => import('./nanoid/NanoIdTool.vue'),
  },
  {
    id: 'qr-code',
    title: 'QR Code 生成',
    description: '把文本或 URL 本地编码为 SVG 或 PNG Data URL QR Code。',
    path: '/tools/qr-code',
    category: 'generate',
    group: 'QR Code',
    keywords: ['qr', 'qrcode', 'code', 'generator', 'url'],
    aliases: ['qr generator', 'qrcode'],
    order: 10,
    status: 'active',
    component: () => import('./qr-code/QrCodeTool.vue'),
  },
  {
    id: 'palette',
    title: '调色板生成',
    description: '从基础颜色生成互补色、邻近色、三角色、浅色和深色。',
    path: '/tools/palette',
    category: 'generate',
    group: 'Color',
    keywords: ['color', 'palette', 'harmony', 'tint', 'shade'],
    aliases: ['palette generator', 'color harmony'],
    order: 50,
    status: 'active',
    component: () => import('./palette/PaletteTool.vue'),
  },
  {
    id: 'password',
    title: '密码生成器',
    description: '生成可配置长度、字符集和易混淆字符策略的随机密码。',
    path: '/tools/password',
    category: 'generate',
    group: 'Password',
    keywords: ['password', 'random', 'generator', 'secure', 'secret'],
    aliases: ['password generator', 'random password'],
    order: 10,
    status: 'active',
    component: () => import('./password/PasswordTool.vue'),
  },
  {
    id: 'passphrase',
    title: 'Passphrase 生成器',
    description: '从内置词表生成易记的随机 passphrase。',
    path: '/tools/passphrase',
    category: 'generate',
    group: 'Password',
    keywords: ['passphrase', 'password', 'diceware', 'words', 'generator'],
    aliases: ['passphrase generator', 'diceware'],
    order: 20,
    status: 'active',
    component: () => import('./passphrase/PassphraseTool.vue'),
  },
  {
    id: 'lorem-ipsum',
    title: 'Lorem Ipsum 生成器',
    description: '生成可配置段落、句子和词数的占位文本。',
    path: '/tools/lorem-ipsum',
    category: 'generate',
    group: 'Mock Data',
    keywords: ['lorem', 'ipsum', 'placeholder', 'text', 'mock'],
    aliases: ['lorem ipsum', 'dummy text'],
    order: 10,
    status: 'active',
    component: () => import('./lorem-ipsum/LoremIpsumTool.vue'),
  },
  {
    id: 'mock-json',
    title: 'Mock JSON 数据生成',
    description: '按紧凑 schema token 或样例形状生成 mock JSON。',
    path: '/tools/mock-json',
    category: 'generate',
    group: 'Mock Data',
    keywords: ['mock', 'json', 'faker', 'sample', 'data'],
    aliases: ['mock data', 'json faker'],
    order: 20,
    status: 'active',
    component: () => import('./mock-json/MockJsonTool.vue'),
  },
  {
    id: 'random-string',
    title: '随机字符串生成器',
    description: '按预设或自定义字符集生成随机字符串。',
    path: '/tools/random-string',
    category: 'generate',
    group: 'Random',
    keywords: ['random', 'string', 'chars', 'token', 'generator'],
    aliases: ['random text', 'random chars'],
    order: 10,
    status: 'active',
    component: () => import('./random-string/RandomStringTool.vue'),
  },
  {
    id: 'json-type',
    title: 'JSON 转类型',
    description: '从 JSON 样例生成 TypeScript、Java、Go 和 Zod 类型。',
    path: '/tools/json-type',
    category: 'code',
    group: 'Types',
    keywords: ['json', 'type', 'typescript', 'interface', 'java', 'go', 'zod', 'schema'],
    aliases: ['interface generator', 'schema generator', 'pojo', 'struct'],
    featured: true,
    order: 10,
    status: 'active',
    component: () => import('./json-type/JsonTypeTool.vue'),
  },
  {
    id: 'jsonpath',
    title: 'JSONPath 查询器',
    description: '用 JSONPath 表达式查询 JSON，并复制命中路径和值。',
    path: '/tools/jsonpath',
    category: 'code',
    group: 'Query',
    keywords: ['jsonpath', 'json', 'query', 'path', 'filter'],
    aliases: ['json query', 'json path tester'],
    order: 30,
    status: 'active',
    component: () => import('./jsonpath/JsonPathTool.vue'),
  },
  {
    id: 'json-schema-generate',
    title: 'JSON Schema 生成器',
    description: '从 JSON 样例推断基础 JSON Schema。',
    path: '/tools/json-schema-generate',
    category: 'code',
    group: 'Schema',
    keywords: ['json', 'schema', 'generate', 'infer'],
    aliases: ['schema generator', 'json schema infer'],
    order: 40,
    status: 'active',
    component: () => import('./json-schema-generate/JsonSchemaGenerateTool.vue'),
  },
  {
    id: 'json-patch',
    title: 'JSON Patch / Merge Patch',
    description: '对比两个 JSON 文档并生成 JSON Patch 或 Merge Patch。',
    path: '/tools/json-patch',
    category: 'code',
    group: 'JSON / YAML',
    keywords: ['json', 'patch', 'merge patch', 'diff'],
    aliases: ['json diff', 'rfc6902', 'rfc7396'],
    order: 50,
    status: 'active',
    component: () => import('./json-patch/JsonPatchTool.vue'),
  },
  {
    id: 'openapi-viewer',
    title: 'OpenAPI Viewer / Validator',
    description: '解析 OpenAPI YAML/JSON，检查必需字段并汇总 path operation。',
    path: '/tools/openapi-viewer',
    category: 'code',
    group: 'API Schema',
    keywords: ['openapi', 'swagger', 'api', 'schema', 'validator'],
    aliases: ['openapi validator', 'swagger viewer'],
    order: 10,
    status: 'active',
    component: () => import('./openapi-viewer/OpenApiViewerTool.vue'),
  },
  {
    id: 'graphql-variables',
    title: 'GraphQL Variables 合并检查',
    description: '对比 GraphQL 操作定义和 variables JSON，找出缺失与未使用变量。',
    path: '/tools/graphql-variables',
    category: 'code',
    group: 'API Schema',
    keywords: ['graphql', 'variables', 'gql', 'json', 'schema'],
    aliases: ['graphql variables', 'gql variables'],
    order: 30,
    status: 'active',
    component: () => import('./graphql-variables/GraphqlVariablesTool.vue'),
  },
  {
    id: 'yaml-json',
    title: 'YAML / JSON 转换',
    description: '在 JSON 和 YAML 配置格式之间互相转换。',
    path: '/tools/yaml-json',
    category: 'format',
    group: 'JSON / YAML',
    keywords: ['yaml', 'json', 'convert', 'config'],
    aliases: ['yml', 'configuration'],
    featured: true,
    order: 20,
    status: 'active',
    component: () => import('./yaml-json/YamlJsonTool.vue'),
  },
  {
    id: 'markdown-preview',
    title: 'Markdown 预览',
    description: '在本地渲染 Markdown，并查看标题结构、字数和 HTML 输出。',
    path: '/tools/markdown-preview',
    category: 'format',
    group: 'Markdown',
    keywords: ['markdown', 'md', 'preview', 'render', 'html'],
    aliases: ['markdown renderer', 'md preview'],
    order: 120,
    status: 'active',
    component: () => import('./markdown-preview/MarkdownPreviewTool.vue'),
  },
  {
    id: 'html',
    title: 'HTML 格式化',
    description: '格式化或压缩 HTML 标记文本。',
    path: '/tools/html',
    category: 'format',
    group: 'Web Markup',
    keywords: ['html', 'format', 'formatter', 'minify', 'markup'],
    aliases: ['html formatter', 'html minifier'],
    order: 130,
    status: 'active',
    component: () => import('./html/HtmlTool.vue'),
  },
  {
    id: 'sitemap',
    title: 'XML Sitemap 格式化',
    description: '格式化并校验 XML Sitemap urlset 或 sitemapindex。',
    path: '/tools/sitemap',
    category: 'format',
    group: 'Web Markup',
    keywords: ['xml', 'sitemap', 'seo', 'urlset', 'sitemapindex'],
    aliases: ['sitemap validator', 'xml sitemap'],
    order: 135,
    status: 'active',
    component: () => import('./sitemap/SitemapTool.vue'),
  },
  {
    id: 'css',
    title: 'CSS 格式化',
    description: '格式化或压缩 CSS 样式代码。',
    path: '/tools/css',
    category: 'format',
    group: 'Web Code',
    keywords: ['css', 'format', 'formatter', 'minify', 'style'],
    aliases: ['css formatter', 'css minifier'],
    order: 140,
    status: 'active',
    component: () => import('./css/CssTool.vue'),
  },
  {
    id: 'js-ts-format',
    title: 'JavaScript / TypeScript 格式化',
    description: '本地格式化 JavaScript 和 TypeScript 源码，不执行输入内容。',
    path: '/tools/js-ts-format',
    category: 'format',
    group: 'Web Code',
    keywords: ['javascript', 'typescript', 'js', 'ts', 'format', 'formatter'],
    aliases: ['javascript formatter', 'typescript formatter'],
    order: 150,
    status: 'active',
    component: () => import('./js-ts-format/JsTsFormatTool.vue'),
  },
  {
    id: 'color',
    title: 'Color Picker / 转换',
    description: '在 HEX、RGB、HSL 和 OKLCH 之间转换颜色。',
    path: '/tools/color',
    category: 'format',
    group: 'Color',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'oklch'],
    aliases: ['color converter', 'hex rgb hsl'],
    order: 160,
    status: 'active',
    component: () => import('./color/ColorTool.vue'),
  },
  {
    id: 'contrast',
    title: '对比度检查器',
    description: '计算前景色和背景色的 WCAG 对比度，并标记 AA / AAA 通过情况。',
    path: '/tools/contrast',
    category: 'format',
    group: 'Color',
    keywords: ['color', 'contrast', 'wcag', 'accessibility', 'aa', 'aaa'],
    aliases: ['contrast checker', 'wcag contrast'],
    order: 170,
    status: 'active',
    component: () => import('./contrast/ContrastTool.vue'),
  },
  {
    id: 'graphql-format',
    title: 'GraphQL Formatter',
    description: '格式化常见 GraphQL query、mutation 和 selection set。',
    path: '/tools/graphql-format',
    category: 'format',
    group: 'API Schema',
    keywords: ['graphql', 'gql', 'format', 'formatter', 'api'],
    aliases: ['graphql formatter', 'gql format'],
    order: 20,
    status: 'active',
    component: () => import('./graphql-format/GraphqlFormatTool.vue'),
  },
  {
    id: 'markdown-toc',
    title: 'Markdown TOC 生成',
    description: '从 Markdown 标题生成可复制的目录链接。',
    path: '/tools/markdown-toc',
    category: 'text',
    group: 'Markdown',
    keywords: ['markdown', 'toc', 'heading', 'anchor', 'docs'],
    aliases: ['markdown toc', 'table of contents'],
    order: 40,
    status: 'active',
    component: () => import('./markdown-toc/MarkdownTocTool.vue'),
  },
  {
    id: 'cron',
    title: 'Cron 表达式解析',
    description: '解析 Cron 表达式并计算下一批执行时间。',
    path: '/tools/cron',
    category: 'time',
    group: 'Schedule',
    keywords: ['cron', 'schedule', 'time', 'crontab'],
    aliases: ['scheduler', 'next run'],
    order: 20,
    status: 'active',
    component: () => import('./cron/CronTool.vue'),
  },
  {
    id: 'curl',
    title: 'cURL 转代码',
    description: '把常见 cURL 请求转换为 Fetch、Axios 或 Python requests。',
    path: '/tools/curl',
    category: 'code',
    group: 'HTTP',
    keywords: ['curl', 'fetch', 'axios', 'python', 'requests', 'http'],
    aliases: ['api client', 'request code'],
    featured: true,
    order: 20,
    status: 'active',
    component: () => import('./curl/CurlTool.vue'),
  },
  {
    id: 'url-parser',
    title: 'URL 解析器',
    description: '解析 URL 的协议、账号、主机、路径、hash 和 query 参数。',
    path: '/tools/url-parser',
    category: 'code',
    group: 'HTTP',
    keywords: ['url', 'uri', 'parse', 'http', 'query'],
    aliases: ['url parse', 'uri parser'],
    order: 30,
    status: 'active',
    component: () => import('./url-parser/UrlParserTool.vue'),
  },
  {
    id: 'query-editor',
    title: 'Query 参数编辑器',
    description: '解析、重建和更新 URL query 参数。',
    path: '/tools/query-editor',
    category: 'code',
    group: 'HTTP',
    keywords: ['query', 'url', 'params', 'parameters', 'search'],
    aliases: ['query params', 'url parameters'],
    order: 40,
    status: 'active',
    component: () => import('./query-editor/QueryEditorTool.vue'),
  },
  {
    id: 'http-headers',
    title: 'HTTP Header 解析器',
    description: '把原始 HTTP 请求或响应头解析成有序列表和 JSON。',
    path: '/tools/http-headers',
    category: 'code',
    group: 'HTTP',
    keywords: ['http', 'headers', 'request', 'response', 'parser'],
    aliases: ['header parser', 'http headers'],
    order: 50,
    status: 'active',
    component: () => import('./http-headers/HttpHeadersTool.vue'),
  },
  {
    id: 'cookie-parser',
    title: 'Cookie 解析器',
    description: '解析 Cookie 请求头或 Set-Cookie 响应头，并展开属性。',
    path: '/tools/cookie-parser',
    category: 'code',
    group: 'HTTP',
    keywords: ['cookie', 'set-cookie', 'http', 'header', 'parser'],
    aliases: ['cookie parser', 'set-cookie'],
    order: 60,
    status: 'active',
    component: () => import('./cookie-parser/CookieParserTool.vue'),
  },
  {
    id: 'user-agent',
    title: 'User-Agent 解析器',
    description: '解析常见浏览器 User-Agent 的浏览器、引擎、系统和设备类型。',
    path: '/tools/user-agent',
    category: 'code',
    group: 'HTTP',
    keywords: ['user-agent', 'ua', 'browser', 'os', 'device'],
    aliases: ['user agent parser', 'ua parser'],
    order: 70,
    status: 'active',
    component: () => import('./user-agent/UserAgentTool.vue'),
  },
  {
    id: 'websocket-echo',
    title: 'WebSocket Echo Client',
    description: '连接 ws:// 或 wss:// 端点，发送消息并记录收发 transcript。',
    path: '/tools/websocket-echo',
    category: 'code',
    group: 'HTTP',
    keywords: ['websocket', 'ws', 'echo', 'client', 'network'],
    aliases: ['websocket client', 'ws echo'],
    order: 80,
    status: 'active',
    component: () => import('./websocket-echo/WebSocketEchoTool.vue'),
  },
  {
    id: 'har-viewer',
    title: 'HAR Viewer',
    description: '解析浏览器导出的 HAR JSON，汇总请求、状态、MIME、大小和耗时。',
    path: '/tools/har-viewer',
    category: 'code',
    group: 'HTTP',
    keywords: ['har', 'network', 'http', 'browser', 'log'],
    aliases: ['har parser', 'network log'],
    order: 90,
    status: 'active',
    component: () => import('./har-viewer/HarViewerTool.vue'),
  },
  {
    id: 'dns-query',
    title: 'DNS 查询',
    description: '构造 DNS-over-HTTPS 查询 URL，并可在浏览器中发起常见 DNS 记录查询。',
    path: '/tools/dns-query',
    category: 'code',
    group: 'Network',
    keywords: ['dns', 'doh', 'lookup', 'network', 'record'],
    aliases: ['dns lookup', 'doh query'],
    order: 10,
    status: 'active',
    component: () => import('./dns-query/DnsQueryTool.vue'),
  },
  {
    id: 'sql',
    title: 'SQL 格式化',
    description: '格式化或压缩 SQL 查询片段。',
    path: '/tools/sql',
    category: 'format',
    group: 'Database',
    keywords: ['sql', 'format', 'formatter', 'query'],
    aliases: ['database', 'mysql', 'postgres'],
    featured: true,
    order: 30,
    status: 'active',
    component: () => import('./sql/SqlTool.vue'),
  },
  {
    id: 'xml',
    title: 'XML 格式化',
    description: '格式化、压缩并校验 XML 文档。',
    path: '/tools/xml',
    category: 'format',
    group: 'XML',
    keywords: ['xml', 'format', 'formatter', 'minify', 'validate'],
    aliases: ['xml formatter', 'xml validator'],
    order: 50,
    status: 'active',
    component: () => import('./xml/XmlTool.vue'),
  },
  {
    id: 'xml-json',
    title: 'XML / JSON 转换',
    description: '在 XML 和 JSON 表示之间互相转换。',
    path: '/tools/xml-json',
    category: 'format',
    group: 'XML',
    keywords: ['xml', 'json', 'convert', 'transform'],
    aliases: ['xml to json', 'json to xml'],
    order: 60,
    status: 'active',
    component: () => import('./xml-json/XmlJsonTool.vue'),
  },
  {
    id: 'xml-xpath',
    title: 'XML 校验 / XPath 测试',
    description: '校验 XML 并执行 XPath 表达式查看匹配节点。',
    path: '/tools/xml-xpath',
    category: 'format',
    group: 'XML',
    keywords: ['xml', 'xpath', 'validate', 'query'],
    aliases: ['xpath tester', 'xml query'],
    order: 70,
    status: 'active',
    component: () => import('./xml-xpath/XmlXPathTool.vue'),
  },
  {
    id: 'toml',
    title: 'TOML 格式化 / JSON 转换',
    description: '格式化 TOML，并在 TOML 与 JSON 之间转换。',
    path: '/tools/toml',
    category: 'format',
    group: 'Config',
    keywords: ['toml', 'json', 'config', 'format', 'convert'],
    aliases: ['toml formatter', 'toml to json'],
    order: 80,
    status: 'active',
    component: () => import('./toml/TomlTool.vue'),
  },
  {
    id: 'ini-properties',
    title: 'INI / Properties 转换',
    description: '在 INI、Java properties 和 JSON 对象之间转换。',
    path: '/tools/ini-properties',
    category: 'format',
    group: 'Config',
    keywords: ['ini', 'properties', 'json', 'config', 'convert'],
    aliases: ['ini converter', 'properties converter'],
    order: 90,
    status: 'active',
    component: () => import('./ini-properties/IniPropertiesTool.vue'),
  },
  {
    id: 'env-convert',
    title: '.env 解析 / JSON 转换',
    description: '解析 .env 配置，并在 .env 与扁平 JSON 对象之间转换。',
    path: '/tools/env-convert',
    category: 'format',
    group: 'Config',
    keywords: ['env', 'dotenv', 'json', 'config', 'convert'],
    aliases: ['.env parser', 'env to json'],
    order: 100,
    status: 'active',
    component: () => import('./env-convert/EnvConvertTool.vue'),
  },
  {
    id: 'csv-json',
    title: 'CSV / JSON 转换',
    description: '在 CSV 文本和 JSON 对象数组之间转换。',
    path: '/tools/csv-json',
    category: 'format',
    group: 'CSV',
    keywords: ['csv', 'json', 'convert', 'table'],
    aliases: ['csv to json', 'json to csv'],
    order: 100,
    status: 'active',
    component: () => import('./csv-json/CsvJsonTool.vue'),
  },
  {
    id: 'csv-table',
    title: 'CSV 表格查看器',
    description: '预览 CSV、TSV 和自定义分隔符表格，检查表头与列数问题。',
    path: '/tools/csv-table',
    category: 'format',
    group: 'CSV',
    keywords: ['csv', 'tsv', 'table', 'preview', 'delimiter'],
    aliases: ['csv viewer', 'table preview'],
    order: 110,
    status: 'active',
    component: () => import('./csv-table/CsvTableTool.vue'),
  },
  {
    id: 'csv-sql',
    title: 'CSV / SQL INSERT 生成',
    description: '把 CSV 数据转换成可复制的多行 SQL INSERT 语句。',
    path: '/tools/csv-sql',
    category: 'code',
    group: 'Database',
    keywords: ['csv', 'sql', 'insert', 'database', 'seed'],
    aliases: ['csv to sql', 'insert generator'],
    order: 35,
    status: 'active',
    component: () => import('./csv-sql/CsvSqlTool.vue'),
  },
  {
    id: 'connection-string',
    title: '连接字符串解析器',
    description: '解析数据库 URL 形态连接字符串，并输出脱敏版本。',
    path: '/tools/connection-string',
    category: 'code',
    group: 'Database',
    keywords: ['database', 'connection', 'url', 'postgres', 'mysql', 'redis', 'mongo'],
    aliases: ['database url', 'connection string'],
    order: 45,
    status: 'active',
    component: () => import('./connection-string/ConnectionStringTool.vue'),
  },
  {
    id: 'sql-bind',
    title: 'SQL 参数绑定预览',
    description: '用 JSON 数组替换 SQL 中的 ? 占位符，生成可读 SQL 预览。',
    path: '/tools/sql-bind',
    category: 'code',
    group: 'Database',
    keywords: ['sql', 'bind', 'parameters', 'placeholder', 'database'],
    aliases: ['sql bind', 'sql parameters'],
    order: 55,
    status: 'active',
    component: () => import('./sql-bind/SqlBindTool.vue'),
  },
  {
    id: 'mongo-objectid',
    title: 'Mongo ObjectId 解析',
    description: '解析 24 位 Mongo ObjectId 中的时间戳、随机值和计数器字段。',
    path: '/tools/mongo-objectid',
    category: 'code',
    group: 'Database',
    keywords: ['mongo', 'mongodb', 'objectid', 'timestamp', 'database'],
    aliases: ['objectid parser', 'mongo id'],
    order: 65,
    status: 'active',
    component: () => import('./mongo-objectid/MongoObjectIdTool.vue'),
  },
  {
    id: 'redis-command',
    title: 'Redis 命令格式化',
    description: '把 Redis 命令切分为 token，并生成 RESP 协议预览。',
    path: '/tools/redis-command',
    category: 'code',
    group: 'Database',
    keywords: ['redis', 'resp', 'command', 'database', 'formatter'],
    aliases: ['redis resp', 'redis formatter'],
    order: 75,
    status: 'active',
    component: () => import('./redis-command/RedisCommandTool.vue'),
  },
  {
    id: 'docker-compose',
    title: 'Docker Compose 校验 / 展开',
    description: '解析 Compose YAML，检查 services 并展开端口、环境变量和依赖摘要。',
    path: '/tools/docker-compose',
    category: 'code',
    group: 'DevOps',
    keywords: ['docker', 'compose', 'yaml', 'devops', 'services'],
    aliases: ['compose validator', 'docker compose'],
    order: 10,
    status: 'active',
    component: () => import('./docker-compose/DockerComposeTool.vue'),
  },
  {
    id: 'kubernetes-yaml',
    title: 'Kubernetes YAML 快速检查',
    description: '解析多文档 Kubernetes YAML，检查核心字段并汇总资源。',
    path: '/tools/kubernetes-yaml',
    category: 'code',
    group: 'DevOps',
    keywords: ['kubernetes', 'k8s', 'yaml', 'manifest', 'devops'],
    aliases: ['k8s yaml', 'kubernetes validator'],
    order: 20,
    status: 'active',
    component: () => import('./kubernetes-yaml/KubernetesYamlTool.vue'),
  },
  {
    id: 'semver',
    title: 'SemVer 比较器',
    description: '比较语义化版本，并检查常见版本范围是否匹配。',
    path: '/tools/semver',
    category: 'code',
    group: 'Release',
    keywords: ['semver', 'version', 'release', 'range', 'compare'],
    aliases: ['semantic version', 'version range'],
    order: 10,
    status: 'active',
    component: () => import('./semver/SemverTool.vue'),
  },
  {
    id: 'json-schema-validate',
    title: 'JSON Schema 校验',
    description: '用 JSON Schema 在本地校验 JSON 数据并定位错误路径。',
    path: '/tools/json-schema-validate',
    category: 'format',
    group: 'Schema',
    keywords: ['json', 'schema', 'validate', 'validator'],
    aliases: ['json schema validator', 'schema validation'],
    order: 40,
    status: 'active',
    component: () => import('./json-schema-validate/JsonSchemaValidateTool.vue'),
  },
  {
    id: 'regex',
    title: '正则测试',
    description: '用示例文本测试正则表达式。',
    path: '/tools/regex',
    category: 'text',
    group: 'Text Analysis',
    keywords: ['regex', 'regexp', 'pattern', 'match'],
    aliases: ['regular expression'],
    order: 10,
    status: 'active',
    component: () => import('./regex/RegexTool.vue'),
  },
  {
    id: 'regex-helper',
    title: '正则解释 / 生成辅助',
    description: '解释常见正则 token，并从常用预设生成表达式。',
    path: '/tools/regex-helper',
    category: 'text',
    group: 'Text Analysis',
    keywords: ['regex', 'regexp', 'explain', 'builder', 'preset'],
    aliases: ['regex explain', 'regex builder'],
    order: 15,
    status: 'active',
    component: () => import('./regex-helper/RegexHelperTool.vue'),
  },
  {
    id: 'diff',
    title: '文本对比',
    description: '在浏览器中对比两段文本。',
    path: '/tools/diff',
    category: 'text',
    group: 'Text Analysis',
    keywords: ['diff', 'compare', 'text'],
    aliases: ['compare text', 'line diff'],
    order: 20,
    status: 'active',
    component: () => import('./diff/DiffTool.vue'),
  },
  {
    id: 'text-stats',
    title: '文本统计',
    description: '统计字符、词、行、段落、句子、UTF-8 字节和唯一词数量。',
    path: '/tools/text-stats',
    category: 'text',
    group: 'Text Analysis',
    keywords: ['text', 'stats', 'word', 'character', 'count', 'bytes'],
    aliases: ['word count', 'character count'],
    order: 25,
    status: 'active',
    component: () => import('./text-stats/TextStatsTool.vue'),
  },
  {
    id: 'case',
    title: '命名格式转换',
    description: '在常见命名格式之间转换文本。',
    path: '/tools/case',
    category: 'text',
    group: 'Text Transform',
    keywords: ['case', 'camel', 'snake', 'kebab', 'pascal'],
    aliases: ['naming', 'identifier'],
    order: 30,
    status: 'active',
    component: () => import('./case/CaseTool.vue'),
  },
  {
    id: 'slug',
    title: 'Slug 生成',
    description: '把标题或文件名转换为 URL 安全 slug，支持分隔符、大小写和长度限制。',
    path: '/tools/slug',
    category: 'text',
    group: 'Text Transform',
    keywords: ['slug', 'url', 'title', 'filename', 'seo'],
    aliases: ['slug generator', 'url slug'],
    order: 40,
    status: 'active',
    component: () => import('./slug/SlugTool.vue'),
  },
  {
    id: 'pinyin',
    title: '拼音转换',
    description: '使用内置常用汉字映射把中文文本转换为拼音。',
    path: '/tools/pinyin',
    category: 'text',
    group: 'Text Transform',
    keywords: ['pinyin', 'chinese', 'hanzi', 'slug', 'transliteration'],
    aliases: ['chinese pinyin', 'hanzi pinyin'],
    order: 50,
    status: 'active',
    component: () => import('./pinyin/PinyinTool.vue'),
  },
  {
    id: 'template-replace',
    title: '文本模板替换',
    description: '用 JSON 对象或对象数组批量替换 {{变量}} 占位符。',
    path: '/tools/template-replace',
    category: 'text',
    group: 'Text Transform',
    keywords: ['template', 'replace', 'variables', 'batch', 'text'],
    aliases: ['template replace', 'variable replacement'],
    order: 60,
    status: 'active',
    component: () => import('./template-replace/TemplateReplaceTool.vue'),
  },
  {
    id: 'line-tools',
    title: '行排序 / 去重',
    description: '对多行文本执行修剪、去空行、排序和去重。',
    path: '/tools/line-tools',
    category: 'text',
    group: 'List',
    keywords: ['line', 'sort', 'unique', 'dedupe', 'list'],
    aliases: ['line sort', 'dedupe lines'],
    order: 10,
    status: 'active',
    component: () => import('./line-tools/LineToolsTool.vue'),
  },
  {
    id: 'list-random',
    title: '列表随机化 / 抽样',
    description: '对多行列表洗牌，或按样本数量抽取随机子集。',
    path: '/tools/list-random',
    category: 'text',
    group: 'List',
    keywords: ['list', 'shuffle', 'random', 'sample', 'lines'],
    aliases: ['shuffle list', 'random sample'],
    order: 20,
    status: 'active',
    component: () => import('./list-random/ListRandomTool.vue'),
  },
  {
    id: 'delimiter-convert',
    title: '分隔符转换',
    description: '在换行、逗号、Tab、空格和自定义分隔符之间转换列表。',
    path: '/tools/delimiter-convert',
    category: 'text',
    group: 'List',
    keywords: ['delimiter', 'separator', 'list', 'csv', 'newline'],
    aliases: ['delimiter converter', 'list separator'],
    order: 30,
    status: 'active',
    component: () => import('./delimiter-convert/DelimiterConvertTool.vue'),
  },
  {
    id: 'string-escape',
    title: '字符串转义',
    description: '在 JSON、JavaScript、Python 和 SQL 字符串内容之间执行转义与反转义。',
    path: '/tools/string-escape',
    category: 'text',
    group: 'String Escape',
    keywords: ['string', 'escape', 'unescape', 'json', 'sql', 'javascript', 'python'],
    aliases: ['string escape', 'json escape'],
    order: 10,
    status: 'active',
    component: () => import('./string-escape/StringEscapeTool.vue'),
  },
  {
    id: 'extractor',
    title: '提取 URL / 邮箱 / IP',
    description: '从文本中提取 URL、邮箱、IPv4 和 IPv6，并按类型去重输出。',
    path: '/tools/extractor',
    category: 'text',
    group: 'Extractor',
    keywords: ['extract', 'url', 'email', 'ip', 'ipv4', 'ipv6'],
    aliases: ['extract urls', 'email extractor'],
    order: 10,
    status: 'active',
    component: () => import('./extractor/ExtractorTool.vue'),
  },
]

const mergedToolTargets: Record<string, string> = {
  brotli: 'gzip',
  'qr-decode': 'qr-code',
  'jwt-sign': 'jwt',
  csr: 'x509-cert',
  'rsa-sign': 'rsa-key',
  hmac: 'hash',
  snowflake: 'uuid',
  ulid: 'uuid',
  nanoid: 'uuid',
  palette: 'color',
  contrast: 'color',
  passphrase: 'password',
  'random-string': 'password',
  'graphql-variables': 'graphql-format',
  'markdown-toc': 'markdown-preview',
  'url-parser': 'url',
  'query-editor': 'url',
  'cookie-parser': 'http-headers',
  'user-agent': 'http-headers',
  'xml-json': 'xml',
  'xml-xpath': 'xml',
  'csv-table': 'csv-json',
  'csv-sql': 'csv-json',
  'regex-helper': 'regex',
  slug: 'case',
  pinyin: 'case',
  'list-random': 'line-tools',
  'delimiter-convert': 'line-tools',
  'kubernetes-yaml': 'docker-compose',
  'ip-convert': 'ip-cidr',
}

const mergedToolOverrides: Record<string, Partial<ToolDefinition>> = {
  gzip: {
    title: '压缩 / 解压工作台',
    description: '在同一个工作区执行 Gzip 和 Brotli Base64 压缩与解压。',
    keywords: ['gzip', 'brotli', 'br', 'compression', 'compress', 'decompress', 'base64'],
    aliases: ['gzip decode', 'gzip base64', 'brotli decode', 'br base64'],
    component: () => import('./gzip/CompressionTool.vue'),
  },
  'qr-code': {
    title: 'QR Code 工具',
    description: '生成 QR Code，或从本地图片中识别和解码 QR Code 内容。',
    keywords: ['qr', 'qrcode', 'code', 'generator', 'decode', 'scan', 'image', 'url'],
    aliases: ['qr generator', 'qrcode', 'qr decoder', 'scan qr'],
    component: () => import('./qr-code/QrTool.vue'),
  },
  jwt: {
    title: 'JWT 工作台',
    description: '本地解码 JWT，签发 HMAC JWT，并验证 JWT 签名。',
    keywords: ['jwt', 'token', 'decode', 'header', 'payload', 'sign', 'verify', 'hmac', 'hs256'],
    aliases: ['jsonwebtoken', 'bearer', 'jwt sign', 'jwt verify'],
    component: () => import('./jwt/JwtWorkbenchTool.vue'),
  },
  'ip-cidr': {
    title: 'IP 工具',
    description: '计算 IPv4 CIDR，并转换 IPv4 的整数、HEX、二进制和 IPv4-mapped IPv6 表示。',
    keywords: ['ip', 'cidr', 'subnet', 'network', 'ipv4', 'ipv6', 'integer', 'hex', 'binary'],
    aliases: ['cidr calculator', 'subnet calculator', 'ipv4 converter', 'ipv6 mapped'],
    component: () => import('./ip-cidr/IpTool.vue'),
  },
  'x509-cert': {
    title: '证书 / CSR 解析',
    description: '解析 PEM X.509 证书和证书签名请求的主体、算法、SAN 与有效期信息。',
    keywords: ['x509', 'certificate', 'tls', 'ssl', 'pem', 'san', 'csr', 'certificate request', 'pkcs10'],
    aliases: ['certificate parser', 'tls cert', 'csr parser', 'certificate request'],
    component: () => import('./x509-cert/CertificateTool.vue'),
  },
  'rsa-key': {
    title: 'RSA 工具',
    description: '生成 RSA 公私钥，并使用 RSA PEM 密钥生成或验证签名。',
    keywords: ['rsa', 'key', 'generate', 'pem', 'jwk', 'keypair', 'sign', 'verify', 'signature', 'pss', 'pkcs1'],
    aliases: ['rsa generator', 'rsa keypair', 'rsa verify', 'rsa signature'],
    component: () => import('./rsa-key/RsaTool.vue'),
  },
  hash: {
    title: 'Hash / HMAC',
    description: '生成 SHA 摘要，或使用 SHA 系列算法生成 HMAC 签名。',
    keywords: ['hash', 'sha', 'digest', 'crypto', 'hmac', 'signature', 'secret'],
    aliases: ['sha256', 'checksum', 'hmac sha256', 'signature hash'],
    component: () => import('./hash/DigestTool.vue'),
  },
  uuid: {
    title: 'ID 生成器',
    description: '集中生成和检查 UUID、Snowflake、ULID 与 Nano ID。',
    keywords: ['uuid', 'guid', 'random', 'snowflake', 'ulid', 'nanoid', 'nano id', 'identifier', 'timestamp', 'sortable'],
    aliases: ['id generator', 'twitter snowflake', 'discord snowflake', 'sortable id', 'ulid generator', 'nano id'],
    component: () => import('./uuid/IdTool.vue'),
  },
  color: {
    title: '颜色工作台',
    description: '转换颜色格式，生成调色板，并检查 WCAG 对比度。',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'oklch', 'palette', 'harmony', 'contrast', 'wcag', 'accessibility'],
    aliases: ['color converter', 'hex rgb hsl', 'palette generator', 'color harmony', 'contrast checker', 'wcag contrast'],
    component: () => import('./color/ColorWorkbenchTool.vue'),
  },
  password: {
    title: '密码 / 随机生成',
    description: '生成随机密码、passphrase 和自定义字符集随机字符串。',
    keywords: ['password', 'random', 'generator', 'secure', 'secret', 'passphrase', 'diceware', 'words', 'string', 'chars', 'token'],
    aliases: ['password generator', 'random password', 'passphrase generator', 'diceware', 'random text', 'random chars'],
    component: () => import('./password/RandomCredentialTool.vue'),
  },
  'graphql-format': {
    title: 'GraphQL 工作台',
    description: '格式化 GraphQL query / mutation，并检查 variables JSON 是否匹配。',
    keywords: ['graphql', 'gql', 'format', 'formatter', 'api', 'variables', 'json', 'schema'],
    aliases: ['graphql formatter', 'gql format', 'graphql variables', 'gql variables'],
    component: () => import('./graphql-format/GraphqlTool.vue'),
  },
  'markdown-preview': {
    title: 'Markdown 工作台',
    description: '本地渲染 Markdown，查看 HTML 输出，并从标题生成目录链接。',
    keywords: ['markdown', 'md', 'preview', 'render', 'html', 'toc', 'heading', 'anchor', 'docs'],
    aliases: ['markdown renderer', 'md preview', 'markdown toc', 'table of contents'],
    component: () => import('./markdown-preview/MarkdownTool.vue'),
  },
  url: {
    title: 'URL 工作台',
    description: '编码、解码、解析 URL，并编辑 query 参数。',
    keywords: ['url', 'uri', 'encode', 'decode', 'parse', 'http', 'query', 'params', 'parameters', 'search'],
    aliases: ['percent encoding', 'escape', 'url parse', 'uri parser', 'query params', 'url parameters'],
    component: () => import('./url/UrlWorkbenchTool.vue'),
  },
  'http-headers': {
    title: 'HTTP 解析工具',
    description: '解析 HTTP headers、Cookie / Set-Cookie 和 User-Agent。',
    keywords: ['http', 'headers', 'request', 'response', 'parser', 'cookie', 'set-cookie', 'user-agent', 'ua', 'browser', 'os', 'device'],
    aliases: ['header parser', 'http headers', 'cookie parser', 'set-cookie', 'user agent parser', 'ua parser'],
    component: () => import('./http-headers/HttpInspectTool.vue'),
  },
  xml: {
    title: 'XML 工作台',
    description: '格式化、压缩并校验 XML，在 XML / JSON 之间转换，并测试 XPath。',
    keywords: ['xml', 'format', 'formatter', 'minify', 'validate', 'json', 'convert', 'transform', 'xpath', 'query'],
    aliases: ['xml formatter', 'xml validator', 'xml to json', 'json to xml', 'xpath tester', 'xml query'],
    component: () => import('./xml/XmlWorkbenchTool.vue'),
  },
  'csv-json': {
    title: 'CSV 工作台',
    description: '在 CSV 和 JSON 之间转换，预览表格，并生成 SQL INSERT。',
    keywords: ['csv', 'json', 'convert', 'table', 'tsv', 'preview', 'delimiter', 'sql', 'insert', 'database', 'seed'],
    aliases: ['csv to json', 'json to csv', 'csv viewer', 'table preview', 'csv to sql', 'insert generator'],
    component: () => import('./csv-json/CsvTool.vue'),
  },
  'docker-compose': {
    title: 'DevOps YAML 工具',
    description: '检查 Docker Compose 和 Kubernetes YAML，并汇总关键资源信息。',
    keywords: ['docker', 'compose', 'yaml', 'devops', 'services', 'kubernetes', 'k8s', 'manifest'],
    aliases: ['compose validator', 'docker compose', 'k8s yaml', 'kubernetes validator'],
    component: () => import('./docker-compose/DevOpsYamlTool.vue'),
  },
  regex: {
    title: '正则工作台',
    description: '测试正则表达式，解释常见 token，并从预设生成表达式。',
    keywords: ['regex', 'regexp', 'pattern', 'match', 'explain', 'builder', 'preset'],
    aliases: ['regular expression', 'regex explain', 'regex builder'],
    component: () => import('./regex/RegexWorkbenchTool.vue'),
  },
  case: {
    title: '文本命名转换',
    description: '在常见命名格式之间转换文本，生成 slug，并把中文文本转换为拼音。',
    keywords: ['case', 'camel', 'snake', 'kebab', 'pascal', 'slug', 'url', 'title', 'filename', 'seo', 'pinyin', 'chinese', 'hanzi', 'transliteration'],
    aliases: ['naming', 'identifier', 'slug generator', 'url slug', 'chinese pinyin', 'hanzi pinyin'],
    component: () => import('./case/TextTransformTool.vue'),
  },
  'line-tools': {
    title: '列表工具',
    description: '对多行文本执行排序、去重、随机化、抽样和分隔符转换。',
    keywords: ['line', 'sort', 'unique', 'dedupe', 'list', 'shuffle', 'random', 'sample', 'lines', 'delimiter', 'separator', 'csv', 'newline'],
    aliases: ['line sort', 'dedupe lines', 'shuffle list', 'random sample', 'delimiter converter', 'list separator'],
    component: () => import('./line-tools/ListTool.vue'),
  },
}

export const legacyToolRedirects = Object.fromEntries(
  Object.entries(mergedToolTargets).map(([fromId, toId]) => [`/tools/${fromId}`, `/tools/${toId}`]),
) as Record<string, string>

export const tools: ToolDefinition[] = registeredTools
  .filter((tool) => !mergedToolTargets[tool.id])
  .map((tool) => ({
    ...tool,
    ...(mergedToolOverrides[tool.id] ?? {}),
  }))

export function resolveToolId(toolId: string) {
  return mergedToolTargets[toolId] ?? toolId
}

export function resolveToolPath(path: string) {
  return legacyToolRedirects[path] ?? path
}

export function getToolById(toolId: string) {
  return tools.find((tool) => tool.id === toolId)
}

export function getToolByPath(path: string) {
  return tools.find((tool) => tool.path === path)
}
