import type { ToolDefinition } from './types'

export const tools: ToolDefinition[] = [
  {
    id: 'json',
    title: 'JSON 格式化',
    description: '在浏览器中安全地格式化、压缩和校验 JSON。',
    path: '/tools/json',
    category: 'format',
    group: 'JSON / YAML',
    keywords: ['json', 'formatter', 'validator', 'minify'],
    aliases: ['pretty json', 'jsonlint'],
    featured: true,
    order: 10,
    status: 'active',
    component: () => import('./json/JsonTool.vue'),
  },
  {
    id: 'base64',
    title: 'Base64 编解码',
    description: '编码和解码 Base64 文本。',
    path: '/tools/base64',
    category: 'encode',
    group: 'Text Encoding',
    keywords: ['base64', 'encode', 'decode'],
    aliases: ['b64'],
    order: 10,
    status: 'active',
    component: () => import('./base64/Base64Tool.vue'),
  },
  {
    id: 'json-organize',
    title: 'JSON 排序 / 去重',
    description: '递归排序 JSON 键、移除数组重复项，并生成可复制字段路径。',
    path: '/tools/json-organize',
    category: 'format',
    group: 'JSON / YAML',
    keywords: ['json', 'sort', 'dedupe', 'unique', 'path', 'jsonpath'],
    aliases: ['json sort', 'json dedupe', 'json path'],
    order: 15,
    status: 'active',
    component: () => import('./json-organize/JsonOrganizeTool.vue'),
  },
  {
    id: 'url',
    title: 'URL 编解码',
    description: '编码和解码 URL 组件。',
    path: '/tools/url',
    category: 'encode',
    group: 'URL',
    keywords: ['url', 'uri', 'encode', 'decode'],
    aliases: ['percent encoding', 'escape'],
    order: 20,
    status: 'active',
    component: () => import('./url/UrlTool.vue'),
  },
  {
    id: 'timestamp',
    title: '时间戳转换',
    description: '转换 Unix 时间戳和本地日期字符串。',
    path: '/tools/timestamp',
    category: 'time',
    group: 'Date Time',
    keywords: ['time', 'timestamp', 'unix', 'date'],
    aliases: ['epoch', 'unix time'],
    featured: true,
    order: 10,
    status: 'active',
    component: () => import('./timestamp/TimestampTool.vue'),
  },
  {
    id: 'jwt',
    title: 'JWT 解码',
    description: '本地解码 JWT 标头和载荷，不会上传令牌。',
    path: '/tools/jwt',
    category: 'security',
    group: 'Token',
    keywords: ['jwt', 'token', 'decode', 'header', 'payload'],
    aliases: ['jsonwebtoken', 'bearer'],
    featured: true,
    order: 10,
    status: 'active',
    component: () => import('./jwt/JwtTool.vue'),
  },
  {
    id: 'hash',
    title: '哈希生成',
    description: '生成浏览器原生 SHA 摘要。',
    path: '/tools/hash',
    category: 'security',
    group: 'Digest',
    keywords: ['hash', 'sha', 'digest', 'crypto'],
    aliases: ['sha256', 'checksum'],
    order: 20,
    status: 'active',
    component: () => import('./hash/HashTool.vue'),
  },
  {
    id: 'uuid',
    title: 'UUID 生成',
    description: '生成随机 UUID 值。',
    path: '/tools/uuid',
    category: 'generate',
    group: 'Identifiers',
    keywords: ['uuid', 'guid', 'random'],
    aliases: ['id generator'],
    order: 10,
    status: 'active',
    component: () => import('./uuid/UuidTool.vue'),
  },
  {
    id: 'json-type',
    title: 'JSON 转类型',
    description: '从 JSON 样例生成 TypeScript、Java、Go 和 Zod 类型。',
    path: '/tools/json-type',
    category: 'code',
    group: 'Types',
    keywords: ['json', 'type', 'typescript', 'interface', 'java', 'go', 'zod', 'schema'],
    aliases: ['interface generator', 'schema generator', 'pojo', 'struct'],
    featured: true,
    order: 10,
    status: 'active',
    component: () => import('./json-type/JsonTypeTool.vue'),
  },
  {
    id: 'jsonpath',
    title: 'JSONPath 查询器',
    description: '用 JSONPath 表达式查询 JSON，并复制命中路径和值。',
    path: '/tools/jsonpath',
    category: 'code',
    group: 'Query',
    keywords: ['jsonpath', 'json', 'query', 'path', 'filter'],
    aliases: ['json query', 'json path tester'],
    order: 30,
    status: 'active',
    component: () => import('./jsonpath/JsonPathTool.vue'),
  },
  {
    id: 'json-schema-generate',
    title: 'JSON Schema 生成器',
    description: '从 JSON 样例推断基础 JSON Schema。',
    path: '/tools/json-schema-generate',
    category: 'code',
    group: 'Schema',
    keywords: ['json', 'schema', 'generate', 'infer'],
    aliases: ['schema generator', 'json schema infer'],
    order: 40,
    status: 'active',
    component: () => import('./json-schema-generate/JsonSchemaGenerateTool.vue'),
  },
  {
    id: 'json-patch',
    title: 'JSON Patch / Merge Patch',
    description: '对比两个 JSON 文档并生成 JSON Patch 或 Merge Patch。',
    path: '/tools/json-patch',
    category: 'code',
    group: 'JSON / YAML',
    keywords: ['json', 'patch', 'merge patch', 'diff'],
    aliases: ['json diff', 'rfc6902', 'rfc7396'],
    order: 50,
    status: 'active',
    component: () => import('./json-patch/JsonPatchTool.vue'),
  },
  {
    id: 'yaml-json',
    title: 'YAML / JSON 转换',
    description: '在 JSON 和 YAML 配置格式之间互相转换。',
    path: '/tools/yaml-json',
    category: 'format',
    group: 'JSON / YAML',
    keywords: ['yaml', 'json', 'convert', 'config'],
    aliases: ['yml', 'configuration'],
    featured: true,
    order: 20,
    status: 'active',
    component: () => import('./yaml-json/YamlJsonTool.vue'),
  },
  {
    id: 'cron',
    title: 'Cron 表达式解析',
    description: '解析 Cron 表达式并计算下一批执行时间。',
    path: '/tools/cron',
    category: 'time',
    group: 'Schedule',
    keywords: ['cron', 'schedule', 'time', 'crontab'],
    aliases: ['scheduler', 'next run'],
    order: 20,
    status: 'active',
    component: () => import('./cron/CronTool.vue'),
  },
  {
    id: 'curl',
    title: 'cURL 转代码',
    description: '把常见 cURL 请求转换为 Fetch、Axios 或 Python requests。',
    path: '/tools/curl',
    category: 'code',
    group: 'HTTP',
    keywords: ['curl', 'fetch', 'axios', 'python', 'requests', 'http'],
    aliases: ['api client', 'request code'],
    featured: true,
    order: 20,
    status: 'active',
    component: () => import('./curl/CurlTool.vue'),
  },
  {
    id: 'sql',
    title: 'SQL 格式化',
    description: '格式化或压缩 SQL 查询片段。',
    path: '/tools/sql',
    category: 'format',
    group: 'Database',
    keywords: ['sql', 'format', 'formatter', 'query'],
    aliases: ['database', 'mysql', 'postgres'],
    featured: true,
    order: 30,
    status: 'active',
    component: () => import('./sql/SqlTool.vue'),
  },
  {
    id: 'json-schema-validate',
    title: 'JSON Schema 校验',
    description: '用 JSON Schema 在本地校验 JSON 数据并定位错误路径。',
    path: '/tools/json-schema-validate',
    category: 'format',
    group: 'Schema',
    keywords: ['json', 'schema', 'validate', 'validator'],
    aliases: ['json schema validator', 'schema validation'],
    order: 40,
    status: 'active',
    component: () => import('./json-schema-validate/JsonSchemaValidateTool.vue'),
  },
  {
    id: 'regex',
    title: '正则测试',
    description: '用示例文本测试正则表达式。',
    path: '/tools/regex',
    category: 'text',
    group: 'Text Analysis',
    keywords: ['regex', 'regexp', 'pattern', 'match'],
    aliases: ['regular expression'],
    order: 10,
    status: 'active',
    component: () => import('./regex/RegexTool.vue'),
  },
  {
    id: 'diff',
    title: '文本对比',
    description: '在浏览器中对比两段文本。',
    path: '/tools/diff',
    category: 'text',
    group: 'Text Analysis',
    keywords: ['diff', 'compare', 'text'],
    aliases: ['compare text', 'line diff'],
    order: 20,
    status: 'active',
    component: () => import('./diff/DiffTool.vue'),
  },
  {
    id: 'case',
    title: '命名格式转换',
    description: '在常见命名格式之间转换文本。',
    path: '/tools/case',
    category: 'text',
    group: 'Text Transform',
    keywords: ['case', 'camel', 'snake', 'kebab', 'pascal'],
    aliases: ['naming', 'identifier'],
    order: 30,
    status: 'active',
    component: () => import('./case/CaseTool.vue'),
  },
]

export function getToolById(toolId: string) {
  return tools.find((tool) => tool.id === toolId)
}

export function getToolByPath(path: string) {
  return tools.find((tool) => tool.path === path)
}
